FROM python:3.12-slim

# Tetapkan direktori kerja di dalam container
WORKDIR /app

# Salin file requirements terlebih dahulu untuk caching layer
COPY requirements.txt .

# Install dependensi
# Menambahkan gunicorn untuk server produksi
RUN pip install --no-cache-dir -r requirements.txt && pip install gunicorn

# Salin semua file proyek ke dalam direktori kerja
COPY . .

# Ekspos port yang akan digunakan oleh Flask/Gunicorn
EXPOSE 5000

# Perintah untuk menjalankan backend API menggunakan Gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "backend:app"]