FROM python:3.12-slim

# Tetapkan direktori kerja
WORKDIR /app

# Salin dan install requirements
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Salin semua file proyek
COPY . .

# Ekspos port default Streamlit
EXPOSE 8501

# Perintah untuk menjalankan aplikasi Streamlit
# Opsi --server.address=0.0.0.0 diperlukan agar bisa diakses dari luar container
CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]