version: '3.8'

services:
  db-init:
    # Service ini hanya untuk inisialisasi database
    build:
      context: .
      dockerfile: Dockerfile.backend
    # Override perintah default untuk menjalankan skrip populasi
    command: python db/populate_db.py
    volumes:
      - ./db:/app/db # Harus me-mount volume yang sama dengan backend

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: toko_backend
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - ./db:/app/db
    restart: unless-stopped
    # Tambahkan depends_on dengan kondisi
    depends_on:
      db-init:
        # 'service_completed_successfully' berarti backend akan menunggu
        # sampai container db-init selesai berjalan tanpa error.
        condition: service_completed_successfully

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: toko_frontend
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    # Frontend sekarang menunggu backend, yang sudah menunggu db-init
    depends_on:
      - backend
    restart: unless-stopped
    environment:
      - BACKEND_URL=http://backend:5000/chat